// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Footmath",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Footmath",
            targets: ["AppModule"],
            bundleIdentifier: "com.gui.Footmath",
            teamIdentifier: "8JTQ9M4J69",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .sportsGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("8-bit Arcade In.ttf")
            ]
        )
    ]
)